language: cpp
compiler:
    - gcc

os:
    - osx

# use containers
sudo: false

env:
  - TYPE=Release DEVSPACE=$TRAVIS_BUILD_DIR/..

install:
  #zlib preinstalled

  #dcmtk
  - cd $DEVSPACE
  - wget http://draconpern-buildcache.s3.amazonaws.com/dcmtk-$TRAVIS_OS_NAME.zip
  - unzip -q dcmtk-$TRAVIS_OS_NAME.zip

  #openjpeg and fmjpeg2koj
  - cd $DEVSPACE
  - wget http://draconpern-buildcache.s3.amazonaws.com/fmjpeg2koj-$TRAVIS_OS_NAME.zip
  - unzip -q fmjpeg2koj-$TRAVIS_OS_NAME.zip

   #wxWidgets
  - cd $DEVSPACE
  - wget http://draconpern-buildcache.s3.amazonaws.com/wxWidgets-$TRAVIS_OS_NAME.zip
  - unzip -q wxWidgets-$TRAVIS_OS_NAME.zip

  #boost preinstalled

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DwxWidgets_CONFIG_EXECUTABLE=$DEVSPACE/wxWidgets/build$TYPE/wx-config -DBOOST_ROOT=$DEVSPACE/boost -DDCMTK_DIR=$DEVSPACE/dcmtk/$TYPE -DFMJPEG2K=$DEVSPACE/fmjpeg2koj/$TYPE -DOPENJPEG=$DEVSPACE/openjpeg/$TYPE -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9

script:
  - cd $TRAVIS_BUILD_DIR/build-$TYPE
  - make -j8
 
before_deploy:
  - cd $TRAVIS_BUILD_DIR/build-$TYPE
  - hdiutil create -volname dovo -srcfolder $TRAVIS_BUILD_DIR/build-$TYPE/dovo.app -ov -format UDZO dovo.dmg
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir -p dpl_cd_upload
  - mv $TRAVIS_BUILD_DIR/build-$TYPE/dovo.dmg $TRAVIS_BUILD_DIR/../dpl_cd_upload/
deploy:
  provider: s3
  access_key_id: AKIAJLIJS2MGONMUBW4A
  secret_access_key:
     secure: hiqUoDtNLKBEqPNFcXGV7pNaUyjCuNY2a22dzS6AGVXoX1IxHhI5Hnawhfevk+P6NaxGUUVgYOpc53vMtk3ng4EOH93JVysa+NwYQ2u56/Knhl7uhxG4ZGcmvMVLuzQOyBXYxz+n2vvpZRGnfGj8EuteQrA+bAKPwI18S0GxeXI=
  bucket: draconpern-buildcache
  acl: public_read
  skip_cleanup: true
  local_dir: dpl_cd_upload