language: cpp
compiler:
    - gcc

os:
    - osx

# use containers
sudo: false

env:
  - TYPE=Release DEVSPACE=$TRAVIS_BUILD_DIR/..

install:
  #zlib preinstalled

  #dcmtk
  - cd $DEVSPACE
  - "[ -d dcmtk ] || git clone git@github.com:DraconPern/dcmtk.git --branch ci"
  - cd dcmtk && git pull && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DDCMTK_WIDE_CHAR_FILE_IO_FUNCTIONS=1 -DCMAKE_INSTALL_PREFIX=$DEVSPACE/dcmtk/$TYPE
  - make -j8 install

  #openjpeg
  - cd $DEVSPACE
  - wget https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
  - tar -xzf version.2.1.tar.gz
  - cd openjpeg-version.2.1 && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$DEVSPACE/openjpeg/$TYPE
  - make -j8 install

   #wxWidgets
  - cd $DEVSPACE
  - "[ -d wxWidgets ] || git clone --branch=master https://github.com/wxWidgets/wxWidgets.git"
  - cd wxWidgets && git checkout v3.0.2 && mkdir -p build$TYPE && cd build$TYPE
  - ../configure --disable-shared
  - make -j8

  #boost preinstalled

  #fmjpeg2koj
  - cd $DEVSPACE
  - "[ -d fmjpeg2koj ] || git clone --branch=master https://github.com/DraconPern/fmjpeg2koj.git"
  - cd fmjpeg2koj && git pull && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. BUILD_SHARED_LIBS=OFF -DOPENJPEG=$DEVSPACE/openjpeg/$TYPE -DDCMTK_DIR=$DEVSPACE/dcmtk/$TYPE -DCMAKE_INSTALL_PREFIX=$DEVSPACE/fmjpeg2koj/$TYPE
  - make -j8 install

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DwxWidgets_CONFIG_EXECUTABLE=$DEVSPACE/wxWidgets/build$TYPE/wx-config -DBOOST_ROOT=$DEVSPACE/boost -DDCMTK_DIR=$DEVSPACE/dcmtk/$TYPE -DFMJPEG2K=$DEVSPACE/fmjpeg2koj/$TYPE -DOPENJPEG=$DEVSPACE/openjpeg/$TYPE

script:
  - cd $TRAVIS_BUILD_DIR/build-$TYPE
  - make -j8

after_script:
  - hdiutil create -volname dovo -srcfolder $TRAVIS_BUILD_DIR/build-$TYPE/dovo.app -ov -format UDZO dovo.dmg
before_deploy:
  - cd $TRAVIS_BUILD_DIR/..  
  - mkdir -p dpl_cd_upload
  - mv $TRAVIS_BUILD_DIR/build-$TYPE/dovo.dmg $TRAVIS_BUILD_DIR/../dpl_cd_upload/
deploy:
  provider: s3
  access_key_id: AKIAJLIJS2MGONMUBW4A
  secret_access_key:
    secure: t04V7/n5MBI+vPYvd1nw/jAS+BMyFhUHWUBzZR62FpDzXI49vfJ7Bs4UJ340j2AWgoDfz2oij2f5rQIKL09Pd1436XeheHzXBuL8DDAMrGlLC33Z3vJgwCxE7dYTtbzoAZHXrIO86mSU9OGoTPl8oGHcsp/mw6gKws4gkwd4HBpMyq61je7rsbYOUePkhyBR9/+KIkDjqnqyKcayYKwKWbpfdMaGDH4sMqpXxI7fd2TAx/ars905QDkYfQ+sdAdIE4dMmPGSKL072m/Y8NGFgtvuz65mABmC62l11eXDSQG4vqmiSpg9Y+YlLWak8+6pcB2lM63zHcN+SpXBwTNc9zcEZCcDEK78wNzWP9NlsZDYz2Yx4KDSlYyUlCasDzPjwUEyfYm5WgL6ZidufInt0tK0ifJLdM7knrPgWfaVbTu0Th+o5BDzUWFw2Ck9wYXF756j6OJbgzv+N8vFY2cw3gXWRoa6jwIJPxqJsd/xW5YTS3DvQFKxzGmPjX5W5zCRsVbagnVpJ49lm8tsgHeNxjcyaHKXqJa5pt82+Ii2qH2HL8ZzxqHc53KeKg9Cj3vSujLjsrcPQ4gVycBkeSht+4eoe9uMAishDLBjRVd5ESs6tihD1VUSx0YGcvE8LYiV9YieFaV7U8BXc+1zI2B1+FUhcnGP2SnYehKIBYHN8ak=
  bucket: draconpern-buildcache
  acl: public_read
  skip_cleanup: true
  local_dir: dpl_cd_upload