language: cpp
compiler:
    - gcc

os:
    - osx

# use containers
sudo: false

configuration:
  - Release

env:
  - TYPE=Release DEVSPACE=$TRAVIS_BUILD_DIR/..

install:
  #zlib preinstalled

  #dcmtk
  - cd $DEVSPACE
  - "[ -d dcmtk ] || git clone git@github.com:DraconPern/dcmtk.git --branch ci
  - cd dcmtk && git pull && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DDCMTK_WIDE_CHAR_FILE_IO_FUNCTIONS=1 -DCMAKE_INSTALL_PREFIX=$DEVSPACE/dcmtk/$TYPE
  - make -j8 install

  #openjpeg
  - cd $DEVSPACE
  - wget https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
  - tar -xzf version.2.1.tar.gz
  - cd openjpeg-version.2.1 && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$DEVSPACE/openjpeg/$TYPE
  - make -j8 install

   #wxWidgets
  - cd $DEVSPACE
  - "[ -d wxWidgets ] || git clone --branch=master https://github.com/wxWidgets/wxWidgets.git"
  - cd wxWidgets && git checkout v3.0.2 && mkdir -p build$TYPE && cd build$TYPE
  - ../configure --disable-shared
  - make -j8

  #boost preinstalled

  #fmjpeg2koj
  - cd $DEVSPACE
  - "[ -d fmjpeg2koj ] || git clone --branch=master https://github.com/DraconPern/fmjpeg2koj.git"
  - cd fmjpeg2koj && git pull && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. BUILD_SHARED_LIBS=OFF -DOPENJPEG=$DEVSPACE/openjpeg/$TYPE -DDCMTK_DIR=$DEVSPACE/dcmtk/$TYPE -DCMAKE_INSTALL_PREFIX=$DEVSPACE/fmjpeg2koj/$TYPE
  - make -j8 install

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DwxWidgets_CONFIG_EXECUTABLE=$DEVSPACE/wxWidgets/build$TYPE/wx-config -DBOOST_ROOT=$DEVSPACE/boost -DDCMTK_DIR=$DEVSPACE/dcmtk/$TYPE -DFMJPEG2K=$DEVSPACE/fmjpeg2koj/$TYPE -DOPENJPEG=$DEVSPACE/openjpeg/$TYPE

script:
  - cd $TRAVIS_BUILD_DIR/build-$TYPE
  - make -j8

after_script:
  - hdiutil create -volname dovo -srcfolder $TRAVIS_BUILD_DIR/build-$TYPE/dovo.app -ov -format UDZO dovo.dmg

addons:
  artifacts:
    paths:
    - $TRAVIS_BUILD_DIR/build-$TYPE/dovo.dmg
